language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
- sudo apt-get update
install:
- pip install -r dev-requirements.txt
before_script:
- flake8 whoare --count --select=E9,F63,F7,F82 --show-source --statistics
- flake8 whoare --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
- python -m pytest -s
deploy:
  provider: pypi
  username: __token__
  password:
    secure: GRqYkwQU9E67AXt/1c07G7ohGdSESLRjfuxM/G5Fbyd5m34VtgKDK4dlekuLi9ezltGNSqVwDQhjQHJsbk6T9hDPIFkI5YaJn4+5uT3Fkf1ef0o+5dFPxrt4F6eCBEZSbz1B/rbyJshDCiEqOUxFTLu8VheFzmzxsKDr98snZJW67Sfxsi7LWNg4XerO6pPPc3dryaRzNvqCWoDF9sSitoiVQN+ST1++wPCVr1QGdOaM2DeIw/9MfLWsNaB9gfsRe8OfcBJh4SNz0h+50p0G0nfSZl0xqbu4O5flLCLT5aL8jJ9qtwIS8rqSmgPIVYO4z96ClaCYvtSdjEktLTXT9kIdCWB0S6Ag6fBh/ly1japEiKRn8ikbKrh44PpDeQzNlY28GYWHC0TWaBF4Opb66CHMSnS7qAo9geqflakg6KPTDn3yxlaPT4NzoSWlsqHMgIAYsPaxmKoGdK9MQUAWTk0+nQgzHK9dVt5JgSVLJBOrnMk0sKC0xdeDctoTdXhLrrcLiyHYArYz0wnA/tlWbfbaBXBOyycYHuIHPUgr7AhLqdU3OObiBnVDF1H9z9rqLVMYj/8JUoFwiNBx20MgjEQUcCcg8P89x8cexOTfPAa/VMh7XKpY1aQ5NZj4tslcYy1QVS533I4I0VRVbxbI1ZRv9mABwWIyKHPR6IEWKMk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.8
